### ISSUE TITLE
Still missing branding points

### ISSUE THREAD

**Issue by gadLinux** [CDE360/server#7]
We see still some missing points:

We see the social endpoints available over configuration menu. Please delete these or hide it.
![imagen](https://user-images.githubusercontent.com/233204/88739847-e1376100-d13b-11ea-8db6-21307c5f9443.png)

The documentation in help points to Nextcloud, it should point to cde360.io server and cde360 doc. 

![imagen](https://user-images.githubusercontent.com/233204/88739966-31162800-d13c-11ea-8299-b35177483106.png)

URL: https://nextcloud.com/support/ must be https://cde360.io/support/

**Comment by gadLinux** [comment]
PLEASE START YOUR BRANCH FROM THIS TASK FROM 
  /CDE360/cde-branding branch as agreed

The correct way to do it is:
> you are at cde360/server clone

git checkout develop 
git pull
git checkout cde-branding
git pull
git checkout -b feature/7-branding-issues

...

start working. 

Do the PR from feature/7-branding-issues -> cde-branding on CDE360...

**Comment by uploadercde360** [comment]
https://github.com/CDE360/server/tree/7-branding-issues

I made new branch(7-branding-issues) and updated the repo

**Comment by uploadercde360** [comment]
When I do PR from feature/7-branding-issues -> cde-branding on CDE360, it shows 'Can’t automatically merge'
![Screenshot_1](https://user-images.githubusercontent.com/64452359/88811696-75abcd00-d1e9-11ea-8519-6989e5021530.png)

**Comment by gadLinux** [comment]
Deployed. Thank you!

**Comment by uploadercde360** [comment]
Still 1080 Nextcloud words on the server some of them easy to find
